version: '3.8'

services:
  app:
    image: roomio-backends-app:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
      - db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: